version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: music-library-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: tuilakie
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: music_library_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
